version: "3"

services:
  klaatu-android:
    build: 
      dockerfile: Dockerfile.android
    environment:
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
    volumes:
      - ./test_experiments:/code/test_experiments
      - ./tests:/code/tests
    links:
      - ping-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
  ping-server:
    image: ping-server:latest
    ports:
      - "5000:5000"
