# This is a basic workflow that is manually triggered
name: Windows Klaatu Tests
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Experiment Branch'
        default: 'control'
        required: true
        type: string
      slug:
        description: 'Experiment Slug'
        default: 'an-awesome-experiment'
        required: true
        type: string
      user-facing-name:
        description: 'The user facing name'
        default: "An Awesome Experiment"
        required: false
        type: string
env:
  MOZ_HEADLESS: 1
jobs:
  klaatu-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        firefox: ['latest-beta', 'latest-nightly', 'latest' ]
    name: windows-klaatu-firefox${{ matrix.firefox }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup firefox
        id: setup-firefox
        uses: ./.github/actions/setup-firefox/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.firefox }}
      - run: |
          echo Installed firefox versions: ${{ steps.setup-firefox.outputs.firefox-version }}
          ${{ steps.setup-firefox.outputs.firefox-path }} --version
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: browser-actions/setup-geckodriver@latest
      - name: Install Chocolatey
        shell: pwsh
        run: Set-ExecutionPolicy Bypass -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      - name: Install Dependencies
        shell: pwsh
        run: choco install jdk8 selenium 
      - name: Setup tests
        shell: bash
        run: ./setup_script.sh
      - name: Run Tests
        run: tox -e bdd-tests -- --experiment-branch ${{ inputs.branch }} --experiment-slug ${{ inputs.slug }} --private-browsing-enabled
  iOS-klaatu-tests:
    runs-on: macos-latest
    name: iOS Klaatu Tests
    steps:
      - name: Clone firefox-ios repo
        uses: actions/checkout@v4
        with:
            repository: jrbenny35/firefox-ios
            ref: "github-actions-update"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build and setup app
        run: |
          cd firefox-ios
          brew update
          brew install node
          pip3 install virtualenv pipenv
          sh ./bootstrap.sh
      - name: Run Tests
        run: |
          cd firefox-ios/firefox-ios-tests/Tests/ExperimentIntegrationTests
          pipenv install
          EXPERIMENT_NAME="iOS Felt Privacy - Simplified Nav and Felt Deletion v2" pipenv run pytest --experiment ${{ inputs.slug }} -k test_generic.py
          
